In [2]:
import numpy as np
import tensorflow as tf

2023-07-12 21:04:01.731387: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-12 21:04:02.537747: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


## tensors dim

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,1,4])
print(tensor_one_d)

tf.Tensor([2 1 4], shape=(3,), dtype=int32)


In [4]:
tensor_two_d = tf.constant([[2,1,4], [0,2,1]])
print(tensor_two_d)

tf.Tensor(
[[2 1 4]
 [0 2 1]], shape=(2, 3), dtype=int32)


In [7]:
tensor_three_d = tf.constant([
    [[2,1,4], [0,2,1]],
    [[4,7,9], [9,1,3]],
])
print(tensor_three_d)


tf.Tensor(
[[[2 1 4]
  [0 2 1]]

 [[4 7 9]
  [9 1 3]]], shape=(2, 2, 3), dtype=int32)


# operations

## methods

In [12]:
# new type
tensor_one_d = tf.constant([2.0,1,4], dtype=tf.float64)
print(tensor_one_d)

casted_tensor_one_d = tf.cast(tensor_one_d, tf.int32)
print(casted_tensor_one_d)

tf.Tensor([2. 1. 4.], shape=(3,), dtype=float64)
tf.Tensor([2 1 4], shape=(3,), dtype=int32)


In [39]:
# np -> tf
np_array = np.array([1,2,3,4,5])
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)


## eye

In [17]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.float32,
    name=None 
)
print(3* eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [22]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None 
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [25]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=5,
    batch_shape=None,
    dtype=tf.int32,
    name=None 
)
print(eye_tensor)

tf.Tensor(
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]], shape=(3, 5), dtype=int32)


In [37]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=5,
    batch_shape=[2,],
    dtype=tf.int32,
    name=None 
)
print(eye_tensor)

tf.Tensor(
[[[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]

 [[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]], shape=(2, 5, 5), dtype=int32)


## fill

In [35]:
tf.fill([3,4], 8)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]], dtype=int32)>

## ones like

In [42]:
tf.ones_like(tensor_two_d)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

## shape vs size


In [47]:
tf.shape(tensor_two_d).numpy()

array([2, 3], dtype=int32)

In [50]:
tf.size(tensor_two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

## random

In [53]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=5.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[105.400734 103.13779 ]
 [ 92.22952  100.28277 ]
 [ 95.20222  101.531815]], shape=(3, 2), dtype=float32)


In [6]:
random_tensor = tf.random.uniform(
    shape=[5,], 
    minval=8, 
    maxval=None, 
    dtype=tf.float32
)

print(random_tensor)

tf.Tensor([3.4997244 5.540951  6.166817  3.434012  6.8423743], shape=(5,), dtype=float32)


## math

In [11]:
x_abs = tf.constant([-2.25, 2])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 2.  ], dtype=float32)>

In [14]:
tf.sqrt(1123.0)

<tf.Tensor: shape=(), dtype=float32, numpy=33.511192>

In [2]:
a1 = tf.constant([1, 4, 9])
a2 = tf.constant([1, 2, 3])

tf.divide(a1, a2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [6]:
x_argmax = tf.constant(
    [[2, 20, 30, 3, 8],
     [3, 11, 18, 1, 8],
     [14, 45, 23, 5, 27]]
)

tf.math.argmax(x_argmax, axis=1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1])>

In [4]:
tensor_2d = tf.constant(
    [[2, 20, 30, 3, 8],
     [3, 11, 18, 1, 8],
     [14, 45, 23, 5, 27]]
)

tf.math.reduce_sum(tensor_2d, axis=1, keepdims=False)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 63,  41, 114], dtype=int32)>

In [5]:
tf.math.top_k(tensor_2d, k=2)

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[30, 20],
       [18, 11],
       [45, 27]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 1],
       [1, 4]], dtype=int32)>)

## band_part

In [12]:
tensor_2d = tf.constant(
    [[1, -2, 0],
     [1, 5, 6],
     [2, 3, 8]]
)

print(tf.linalg.band_part(tensor_2d, 0, 0)) # keep the main diagonal
print(tf.linalg.band_part(tensor_2d, -1, 0)) # keep the lower triangular 
print(tf.linalg.band_part(tensor_2d, 0, -1)) # keep the upper triangular 

tf.Tensor(
[[1 0 0]
 [0 5 0]
 [0 0 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 0 0]
 [1 5 0]
 [2 3 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 1 -2  0]
 [ 0  5  6]
 [ 0  0  8]], shape=(3, 3), dtype=int32)


## inversion

In [15]:
tensor_2d = tf.constant(
    [[1, -2, 0],
     [1, 5, 6],
     [2, 3, 8]], dtype=tf.float32
)

tf.linalg.inv(tensor_2d)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.5714285 ,  1.1428571 , -0.8571428 ],
       [ 0.2857143 ,  0.5714286 , -0.42857146],
       [-0.5       , -0.5       ,  0.5       ]], dtype=float32)>

In [17]:
tf.linalg.inv(tensor_2d)@tensor_2d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00, -1.1920929e-07,  0.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]], dtype=float32)>

## svd

In [2]:
tensor_2d = tf.constant(
    [[1, -2, 0],
     [1, 5, 6],
     [2, 3, 8]], dtype=tf.float32
)

s, u, v = tf.linalg.svd(tensor_2d)

In [4]:
s

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([11.64254  ,  2.876895 ,  0.4179808], dtype=float32)>

In [5]:
u

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.068646  , -0.7189183 ,  0.6916966 ],
       [ 0.66535825,  0.48362345,  0.56868845],
       [ 0.7433613 , -0.49926424, -0.44513935]], dtype=float32)>

In [6]:
v

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.17895022, -0.42887354,  0.8854628 ],
       [ 0.4890828 ,  0.81968933,  0.2981735 ],
       [ 0.853683  , -0.37970638, -0.35643822]], dtype=float32)>

## einsum

In [12]:
A = np.array(
    [[5, 4, 7, 5],
    [0, 2, 1, 1],
    [8, 5, 5, 1]]
)
B = np.array(
    [[4, 0, 0, 1, 3],
    [5, 0, 0, 0, 7],
    [2, 5, 7, 9, 5],
    [7, 0, 0, 7, 6]]
)

In [14]:
np.matmul(A,B)

array([[ 89,  35,  49, 103, 108],
       [ 19,   5,   7,  16,  25],
       [ 74,  25,  35,  60,  90]])

In [16]:
A@B

array([[ 89,  35,  49, 103, 108],
       [ 19,   5,   7,  16,  25],
       [ 74,  25,  35,  60,  90]])

In [15]:
np.einsum("ij,jk->ik", A, B)

array([[ 89,  35,  49, 103, 108],
       [ 19,   5,   7,  16,  25],
       [ 74,  25,  35,  60,  90]])

In [21]:
C = np.array([
    [4, 6, 0, 8],
    [4, 7, 1, 1],
    [4, 0, 4, 9]])

print(A.shape, C.shape)

(3, 4) (3, 4)


In [23]:
A*C

array([[20, 24,  0, 40],
       [ 0, 14,  1,  1],
       [32,  0, 20,  9]])

In [24]:
np.einsum("ij,ij->ij", A, C)

array([[20, 24,  0, 40],
       [ 0, 14,  1,  1],
       [32,  0, 20,  9]])

In [30]:
A = np.array([[[6, 2, 4, 7],
        [0, 1, 9, 0],
        [5, 2, 4, 0]],

       [[7, 3, 0, 6],
        [3, 3, 5, 0],
        [9, 9, 5, 3]]])

B = np.array([[[0, 1, 0, 4, 0],
        [3, 3, 2, 3, 5],
        [0, 4, 6, 9, 2],
        [4, 5, 4, 7, 2]],

       [[0, 8, 2, 5, 5],
        [6, 6, 8, 4, 3],
        [3, 0, 5, 2, 4],
        [5, 8, 2, 8, 2]]])

In [32]:
np.einsum("bij,bjk -> bik", A, B)

array([[[ 34,  63,  56, 115,  32],
        [  3,  39,  56,  84,  23],
        [  6,  27,  28,  62,  18]],

       [[ 48, 122,  50,  95,  56],
        [ 33,  42,  55,  37,  44],
        [ 84, 150, 121, 115,  98]]])

In [38]:
np.sum(A), np.einsum("bij-> ", A)

(93, 93)

In [40]:
np.einsum("bij-> j", A)

array([30, 20, 27, 16])

In [42]:
np.random.randint(low=0, high=10, size=(1, 4, 4, 1))

array([[[[5],
         [4],
         [1],
         [8]],

        [[5],
         [8],
         [1],
         [4]],

        [[0],
         [9],
         [5],
         [6]],

        [[7],
         [0],
         [1],
         [6]]]])

In [43]:
A = np.array([[[[4, 2],
         [3, 2],
         [7, 8],
         [7, 3]],

        [[0, 9],
         [1, 6],
         [6, 7],
         [8, 6]],

        [[7, 3],
         [2, 8],
         [7, 7],
         [6, 2]],

        [[2, 6],
         [5, 7],
         [8, 0],
         [3, 8]]]])

B = np.array([[[[5],
         [4],
         [1],
         [8]],

        [[5],
         [8],
         [1],
         [4]],

        [[0],
         [9],
         [5],
         [6]],

        [[7],
         [0],
         [1],
         [6]]]])

np.einsum("bcij,bcik->bcjk", A, B)

array([[[[ 95],
         [ 50]],

        [[ 46],
         [124]],

        [[ 89],
         [119]],

        [[ 40],
         [ 90]]]])

## padding

In [6]:
t = tf.constant([
    [1,2,3],
    [7,8,9]
])
paddings = tf.constant([[1,2], [2,3]])

tf.pad(t, paddings, "CONSTANT", constant_values=8)

<tf.Tensor: shape=(5, 8), dtype=int32, numpy=
array([[8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 1, 2, 3, 8, 8, 8],
       [8, 8, 7, 8, 9, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8]], dtype=int32)>

## tf.ragged

In [4]:
tensor_two_d = [[1, 2, 0],
                [3,],
                [1,5,6],
                [2,3]]

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)
tensor_ragged

(4, None)


<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6], [2, 3]]>

In [6]:
tf.ragged.boolean_mask(
    tf.ragged.constant([
        [1, 2, 0],
        [3],
        [1,5,6],
        [2,3]
    ]),
    tf.ragged.constant([
        [True, False, True],
        [False],
        [True, True, False],
        [True, False]
    ])
)

<tf.RaggedTensor [[1, 0], [], [1, 5], [2]]>

In [7]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


## sparse

In [3]:
tensor_sparse = tf.sparse.SparseTensor(
    indices=[[1,1], [4,4]], values=[1,2], dense_shape=[5,5]
)
tensor_sparse

SparseTensor(indices=tf.Tensor(
[[1 1]
 [4 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 5], shape=(2,), dtype=int64))

In [5]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2]], dtype=int32)>

# variables

In [7]:
with tf.device("GPU:0"):
    x_var = tf.Variable(0.2)

In [10]:
with tf.device("CPU:0"):
    x_var = tf.Variable(0.2)

print(x_var.device)

/job:localhost/replica:0/task:0/device:CPU:0
